# annotation of tumor ST data
```{r quality control}
Sample <- "NGBC_5"
OutDir <- paste("../result/01_ST_BC/", Sample, "/", sep = "")
dir.create(OutDir)

### The data can be accessed by downloading them through the Dataset accession numbers provided in Supplemental Table 4.

# ---- read files
Xdata <- Seurat::Read10X("../../data/NGBC/CID44971/CID44971_filtered_count_matrix/", gene.column = 1)
metadata <- read.csv("../../data/NGBC/CID44971/CID44971_metadata.csv")
head(metadata)
table(metadata$Classification)


# ---- create seurat object
XF <- CreateSeuratObject(counts = Xdata, project = Sample, assay = "Spatial")
# read image file
Ximage <- Read10X_Image("../../data/NGBC/CID44971/CID44971_spatial/")
Seurat::DefaultAssay(Ximage) <- "Spatial"
# link matrix and image file
Ximage <- Ximage[colnames(XF)]
XF[["image"]] <- Ximage
TumorST <- XFe
TumorST$classification <- metadata$Classification[match(colnames(TumorST), metadata[, 1])]


# ---- QC
dir.create(paste(OutDir, "QC", sep = ""))
TumorST[["Mito.percent"]] <- PercentageFeatureSet(TumorST, pattern = "^MT-")

pdf(paste(OutDir, "QC/Vlnplot.pdf", sep = ""), width = 6, height = 4)
p <- VlnPlot(TumorST, features = c("nFeature_Spatial", "nCount_Spatial", "Mito.percent"), pt.size = 0, combine = F)
for (i in 1:length(p)) {
  p[[i]] <- p[[i]] + NoLegend() + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0))
}
p <- cowplot::plot_grid(plotlist = p, ncol = 3)
print(p)
dev.off()

pdf(paste(OutDir, "QC/featurplot.pdf", sep = ""), width = 7, height = 7)
p <- SpatialFeaturePlot(TumorST, features = c("nFeature_Spatial", "nCount_Spatial", "Mito.percent"), combine = F)
for (i in 1:length(p)) {
  p[[i]] <- p[[i]] + theme(axis.title.x = element_blank(), axis.text.x = element_text(angle = 0))
}
print(cowplot::plot_grid(plotlist = p, ncol = 3))
dev.off()


# ----- save QC result
QCData <- TumorST@meta.data[, c("nCount_Spatial", "nFeature_Spatial", "Mito.percent")]
openxlsx::write.xlsx(QCData, paste(OutDir, "QC/QCData.xlsx", sep = ""), overwrite = T)

TumorST[["Spatial"]]
TumorST[["image"]]


# ---- plot with annotation
pdf(paste(OutDir, Sample, "_tumor_boundary_spatialplot.pdf", sep = ""), width = 6, height = 4)
SpatialDimPlot(TumorST, group.by = "classification") + scale_fill_brewer(palette = "Paired")
dev.off()

saveRDS(TumorST, paste(OutDir, Sample, "_BoundaryDefine_PC.rds", sep = ""))
```


# hub score
```{r plot function}
plot_feature <- function(celltype, celltype_name, hub_name, marker_list, marker_list_name) {
  ctfeatures <- marker_list %>%
    filter(avg_log2FC > 0 & p_val_adj < 0.05) %>%
    filter(pct.1 - pct.2 > 0.1) %>%
    filter(pct.1 > 0.1) %>%
    filter(cluster %in% celltype) %>%
    group_by(cluster) %>%
    arrange(-avg_log2FC) %>%
    slice(1:10) %>%
    pull(gene) %>%
    unique()
  print(ctfeatures)
  TumorST <- AddhubScore(
    object = TumorST,
    features = list(ctfeatures),
    ctrl = length(ctfeatures),
    name = paste0(celltype_name, ".Score"),
    assay = "Spatial"
  )

  pdf(paste0(OutDir, hub_name, "hub_", marker_list_name, "/", Sample, "_", celltype_name, "_featurplot.pdf"), width = 4, height = 4)
  print(SpatialFeaturePlot(TumorST, features = paste0(celltype_name, ".Score1"), pt.size.factor = 2))
  print(SpatialFeaturePlot(TumorST, features = paste0(celltype_name, ".Score1"), min.cutoff = 0, pt.size.factor = 2))
  dev.off()

  return(TumorST)
}
```

```{r TLS_like hub}
TumorST <- readRDS(paste(OutDir, Sample, "_BoundaryDefine_PC.rds", sep = ""))
colnames(TumorST@meta.data)
TumorST@meta.data <- TumorST@meta.data[, -grep("Score1", colnames(TumorST@meta.data))]

dir.create(paste0(OutDir, "TLS_likehub_PC"))

# ---- TLS_like
# select from PC markers
PC_marker <- read.delim("../../data/marker/pancancer_Primary&Metastasis_markers_strict_selectedsubtypes_20062024.txt")
head(PC_marker)
unique(PC_marker$cluster)
TLS_likefeatures <- PC_marker %>%
  filter(avg_log2FC > 0 & p_val_adj < 0.05) %>%
  filter(pct.1 - pct.2 > 0.1) %>%
  filter(pct.1 > 0.1) %>%
  filter(cluster %in%
    c("CD4+ TFH", "Breg", "GC B","Plasmablast", "IFN Mac", "IgG mature", "IgG immature", "IgA mature", "IgA immature", "mQuiescDC")) %>%
  group_by(cluster) %>%
  arrange(-avg_log2FC) %>%
  slice(1:10) %>%
  pull(gene) %>%
  unique()

# add hub score
TumorST <- AddhubScore(
  object = TumorST,
  features = list(TLS_likefeatures),
  ctrl = length(TLS_likefeatures),
  name = "TLS_like.Score",
  assay = "Spatial"
)
head(TumorST@meta.data)

pdf(paste(OutDir, "TLS_likehub_PC/", Sample, "_TLS_like_featurplot.pdf", sep = ""), width = 4, height = 4)
print(SpatialFeaturePlot(TumorST, features = "TLS_like.Score1", pt.size.factor = 2))
print(SpatialFeaturePlot(TumorST, features = "TLS_like.Score1", min.cutoff = 0, pt.size.factor = 2))
dev.off()


# ---- individual cell type
TumorST <- plot_feature("CD4+ TFH", "CD4Tfh", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature("Breg", "Breg", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature("GC B", "GC B", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature("Plasmablast", "Plasmablast", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature("IFN Mac", "IFNmac", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature(c("IgG mature", "IgG immature"), "IgG", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature(c("IgA mature", "IgA immature"), "IgA", "TLS_like", PC_marker, "PC")
TumorST <- plot_feature("mQuiescDC", "mQDC", "TLS_like", PC_marker, "PC")

head(TumorST@meta.data)
```


## Type1_Immunity hub
```{r Type1_Immunity hub}
dir.create(paste0(OutDir, "Type1_Immunityhub_PC"))

unique(PC_marker$cluster)
Type1_immunityfeatures <- PC_marker %>%
  filter(avg_log2FC > 0 & p_val_adj < 0.05) %>%
  filter(pct.1 - pct.2 > 0.1) %>%
  filter(pct.1 > 0.1) %>%
  filter(cluster %in%
    c("CD4+ TREG", "mRegDC", "Mono-like Mac", "LAM2", "Neutrophils", "AXL_DC", "Inflam Mac", "Lymphatic","CD4+ TH1", "CD8+ TEX", "Prolif T")) %>%
  group_by(cluster) %>%
  arrange(-avg_log2FC) %>%
  slice(1:10) %>%
  pull(gene) %>%
  unique()
TumorST <- AddhubScore(
  object = TumorST,
  features = list(Type1_immunityfeatures),
  ctrl = length(Type1_immunityfeatures),
  name = "Type1_immunity.Score",
  assay = "Spatial"
)
# TumorST$Type1_immunitymean <- apply(TumorST@assays$Spatial@layers$data[rownames(TumorST[["Spatial"]]) %in% Type1_immunityfeatures, ], 2, mean)
TumorST$Type1_immunitymean <- scale(TumorST$Type1_immunity.Score1)
head(TumorST@meta.data)

pdf(paste(OutDir, "Type1_immunityhub_PC/", Sample, "_Type1_immunity_featurplot.pdf", sep = ""), width = 4, height = 4)
print(SpatialFeaturePlot(TumorST, features = "Type1_immunity.Score1", pt.size.factor = 2))
print(SpatialFeaturePlot(TumorST, features = "Type1_immunity.Score1", min.cutoff = 0, pt.size.factor = 2))
print(SpatialFeaturePlot(TumorST, features = "Type1_immunitymean", pt.size.factor = 2))
print(SpatialFeaturePlot(TumorST, features = "Type1_immunitymean", min.cutoff = 0, pt.size.factor = 2))
print(SpatialDimPlot(TumorST, group.by = "classification") + scale_fill_brewer(palette = "Paired"))
dev.off()


# ---- individual cell type
TumorST <- plot_feature("CD4+ TREG", "Treg", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("mRegDC", "mRegDC", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("Mono-like Mac", "MonoMac", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("LAM2", "LAM2", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("Neutrophils", "Neutrophils", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("AXL_DC", "AXLDC", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("Inflam Mac", "InflamMac", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("Lymphatic", "Lymphatic", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("CD4+ TH1", "CD4Th1", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("CD8+ TEX", "CD8Tex", "Type1_immunity", PC_marker, "PC")
TumorST <- plot_feature("Prolif T", "ProlifT", "Type1_immunity", PC_marker, "PC")

head(TumorST@meta.data)
```



# hub correlation heatmap
```{r correlation heatmap}
TumorST <- readRDS("../../result/01_ST_BC/NGBC_5/NGBC_5_BoundaryDefine_PC.rds")

metadf <- as.data.frame(TumorST@meta.data)
metadf <- metadf[, grep("mean", colnames(metadf))]
colnames(metadf)

TLS_corr <- cor(metadf[, colnames(metadf)[grep("mean", colnames(metadf))][c(2:8)]])
rownames(TLS_corr) <- gsub("mean", "", rownames(TLS_corr))
colnames(TLS_corr) <- gsub("mean", "", colnames(TLS_corr))
TLS_pval <- cor.mtest(metadf[, colnames(metadf)[grep("mean", colnames(metadf))][c(2:8)]], conf.level = 0.95)
TLS_pval <- TLS_pval$p
rownames(TLS_pval) <- gsub("mean", "", rownames(TLS_pval))
colnames(TLS_pval) <- gsub("mean", "", colnames(TLS_pval))

Type1_immunity_corr <- cor(metadf[, colnames(metadf)[grep("mean", colnames(metadf))][c(10:20)]])
rownames(Type1_immunity_corr) <- gsub("mean", "", rownames(Type1_immunity_corr))
colnames(Type1_immunity_corr) <- gsub("mean", "", colnames(Type1_immunity_corr))
Type1_immunity_pval <- cor.mtest(metadf[, colnames(metadf)[grep("mean", colnames(metadf))][c(10:20)]], conf.level = 0.95)
Type1_immunity_pval <- Type1_immunity_pval$p
rownames(Type1_immunity_pval) <- gsub("mean", "", rownames(Type1_immunity_corr))
colnames(Type1_immunity_pval) <- gsub("mean", "", colnames(Type1_immunity_corr))

pdf("../../result/01_ST_BC/NGBC_5/NGBC_5_celltype_corr.pdf", width = 6, height = 6)
corrplot(
  corr = TLS_corr,
  method = "square",
  type = "upper",
  tl.pos = "lt",
  tl.col = "black",
  col = rev(COL2("RdBu", 8)),
  p.mat = TLS_pval, sig.level = c(0.001, 0.01, 0.05),
  insig = "label_sig",
  pch.cex = 0.9, pch.col = "black"
)
corrplot(
  corr = TLS_corr,
  method = "number",
  type = "lower",
  add = TRUE,
  col = rev(COL2("RdBu", 8)),
  tl.pos = "n", cl.pos = "n",
  diag = FALSE
)
corrplot(
  corr = Type1_immunity_corr,
  method = "square",
  type = "upper",
  tl.pos = "lt",
  tl.col = "black",
  col = rev(COL2("RdBu", 8)),
  p.mat = Type1_immunity_pval, sig.level = c(0.001, 0.01, 0.05),
  insig = "label_sig",
  pch.cex = 0.9, pch.col = "black"
)
corrplot(
  corr = Type1_immunity_corr,
  method = "number",
  type = "lower",
  add = TRUE,
  col = rev(COL2("RdBu", 8)),
  tl.pos = "n", cl.pos = "n",
  diag = FALSE
)
dev.off()
```